CREATE TABLE IF NOT EXISTS players (
    id bigint generated by default as identity primary key,
    name text NOT NULL UNIQUE,
    student_id text NOT NULL UNIQUE,
    is_active boolean DEFAULT true
);

CREATE TABLE match_results (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now(),
    game_date date,
    student_id text,
    is_win integer,
    memo text,
    foreign key (student_id) references players(student_id)
);
