CREATE TABLE match_results (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now(),
    game_date date,
    player_name text,
    is_win integer,
    memo text
);

-- GM Tool用: 参加者名簿（is_active=true のプレイヤーが参加者リストに表示される）
CREATE TABLE IF NOT EXISTS players (
    id bigint generated by default as identity primary key,
    name text NOT NULL UNIQUE,
    is_active boolean DEFAULT true
);
