# Supabase
[supabase]
url = "https://nbqomiynilrpocyreofi.supabase.co"
key = "sb_publishable_Z1qTKBqsfMqdjAhlvyWSrw_m7U0fIu1"

[auth]
master_password = "jinryunen"    # あなた用（開発者・全権限）
staff_password  = "jinrounin"          # 幹部用（運用担当者）

[email]
account = "keiowerewolf.howl@gmail.com"  # あなたのGmail
password = "pffe kqbz sytu nkix" # さっき取得した16桁のアプリパスワード
